# Generated by Django 6.0.4 on 2026-04-21 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_customuser_foto_perfil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='foto_perfil',
            field=models.ImageField(blank=True, null=True, upload_to='accounts/static/accounts/img/perfil-fotos/'),
        ),
    ]
